#!/usr/bin/env bash

#event ups

set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
thisDir="$(echo "$dir" | rev | cut -d"/" -f1 | rev)"
subDir="${dir%"/$thisDir"}"
scriptDir="$(echo "$subDir" | rev | cut -d"/" -f1 | rev)"
root="${subDir%"/$scriptDir"}"
scriptName="$(basename "$0")"

echo "starting $thisDir $scriptName"

action="$root/script/system/action"
getValue="$root/script/system/getValue"

upsVar="$root/config/ups/var"

wall "ups event:$1"

case $1 in
	ONBATT)
		"$action" "$thisDir" "log" "ONBATT"
		;;
	ONLINE)
		"$action" "$thisDir" "log" "ONLINE"
		;;
	LOWBATT)
		"$action" "$thisDir" "log" "LOWBATT"
		
		shutdown="$("$getValue" "$upsVar" "shutdown=")"

		[ -n "$shutdown" ] && "$dir/$shutdown"
		;;
esac

"$action" "$thisDir" "log" "$scriptName"
echo "$thisDir $scriptName exit 0"
exit 0
