#!/usr/bin/env bash

#remove ups

set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
thisDir="$(echo "$dir" | rev | cut -d"/" -f1 | rev)"
subDir="${dir%"/$thisDir"}"
scriptDir="$(echo "$subDir" | rev | cut -d"/" -f1 | rev)"
root="${subDir%"/$scriptDir"}"
scriptName="$(basename "$0")"

echo "starting $thisDir $scriptName"

action="$root/script/system/action"
getValue="$root/script/system/getValue"

upsVar="$root/config/ups/var"

nutUserName="$("$getValue" "$upsVar" "nutUserName=")"
nutGroupName="$("$getValue" "$upsVar" "nutGroupName=")"
{
	userdel "$nutUserName" &&
	echo "remove user $nutUserName success"
} || {
	echo "remove user $nutUserName fail"
}
{
	groupdel "$nutGroupName" &&
	echo "remove group $nutGroupName success"
} || {
	echo "remove group $nutGroupName fail"
}
#not sure if this works if files still have group priv
[ -d /etc/nut ] && rm -rf /etc/nut
[ -d /var/run/nut ] && rm -rf /var/run/nut

"$action" "$thisDir" "log" "$scriptName"
echo "$thisDir $scriptName exit 0"
exit 0
