#!/usr/bin/env bash

#system priv

#run as root

set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
thisDir="$(echo "$dir" | rev | cut -d"/" -f1 | rev)"
subDir="${dir%"/$thisDir"}"
scriptDir="$(echo "$subDir" | rev | cut -d"/" -f1 | rev)"
root="${subDir%"/$scriptDir"}"
scriptName="$(basename "$0")"

echo "starting $thisDir $scriptName"

action="$dir/action"
getValue="$dir/getValue"

var="$root/config/system/var"

user="$("$getValue" "$var" "user=")"

#get root dirs owner and access

priv="$root/config/system/priv"

dirOwner="$("$getValue" "$priv" "dirOwner=" "$user")"
dirAccess="$("$getValue" "$priv" "dirAccess=" "755")"

rootDirOwner="$("$getValue" "$priv" "rootDirOwner=" "$dirOwner")"
rootDirAccess="$("$getValue" "$priv" "rootDirAccess=" "$dirAccess")"

rootScriptDirOwner="$("$getValue" "$priv" "rootScriptDirOwner=" "$dirOwner")"
rootScriptDirAccess="$("$getValue" "$priv" "rootScriptDirAccess=" "$dirAccess")"

rootConfigDirOwner="$("$getValue" "$priv" "rootConfigDirOwner=" "$dirOwner")"
rootConfigDirAccess="$("$getValue" "$priv" "rootConfigDirAccess=" "$dirAccess")"

rootLogDirOwner="$("$getValue" "$priv" "rootLogDirOwner=" "$dirOwner")"
rootLogDirAccess="$("$getValue" "$priv" "rootLogDirAccess=" "$dirAccess")"

rootResetDirOwner="$("$getValue" "$priv" "rootResetDirOwner=" "$dirOwner")"
rootResetDirAccess="$("$getValue" "$priv" "rootResetDirAccess=" "$dirAccess")"

#set root dirs owner and access 
[ -n "$rootDirOwner" ] && chown "$rootDirOwner" "$root"
[ -n "$rootDirAccess" ] && chmod "$rootDirAccess" "$root"

[ -n "$rootScriptDirOwner" ] && chown "$rootScriptDirOwner" "$root/script"
[ -n "$rootScriptDirAccess" ] && chmod "$rootScriptDirAccess" "$root/script"

[ -n "$rootConfigDirOwner" ] && chown "$rootConfigDirOwner" "$root/config"
[ -n "$rootConfigDirAccess" ] && chmod "$rootConfigDirAccess" "$root/config"

[ -n "$rootLogDirOwner" ] && chown "$rootLogDirOwner" "$root/log"
[ -n "$rootLogDirAccess" ] && chmod "$rootLogDirAccess" "$root/log"

[ -n "$rootResetDirOwner" ] && chown "$rootResetDirOwner" "$root/reset"
[ -n "$rootResetDirAccess" ] && chmod "$rootResetDirAccess" "$root/reset"

"$action" "$thisDir" "log" "$scriptName"
echo "$thisDir $scriptName exit 0"
exit 0
