#!/usr/bin/env bash

#npm remove

set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
thisDir="$(echo "$dir" | rev | cut -d"/" -f1 | rev)"
subDir="${dir%"/$thisDir"}"
scriptDir="$(echo "$subDir" | rev | cut -d"/" -f1 | rev)"
root="${subDir%"/$scriptDir"}"
scriptName="$(basename "$0")"

echo "starting $thisDir $scriptName"

action="$root/script/system/action"
getValue="$root/script/system/getValue"

var="$root/config/nodeJS/var" 

setSize="$("$getValue" "$var" "npmRemoveSize=" "0")"
index="0"

while [ "$index" -lt "$setSize" ]
do
	value="$("$getValue" "$var" "npmRemove$index=")"
	
	if [ -n "$value" ]
	then
		{
      		npm uninstall $value --save &&
			echo "remove $value success"
		} || {
			echo "remove $value fail"
		}
	fi
	index=$((index+1))
done

"$action" "$thisDir" "log" "$scriptName"
echo "$thisDir $scriptName exit 0"
exit 0